services:
  - type: worker
    name: instagram-link-saver-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAX_FILE_SIZE_MB
        value: "50"
      - key: TEMP_EXPIRE_MINUTES
        value: "15"
